import 'package:yendoc/controllers/login_controller.dart';

abstract class LocalizationBase extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'es': {
          'common.yes': 'Sí',
          'common.no': 'No',
          'common.ok': 'Aceptar',
          'common.cancel': 'Cancelar',
          'common.yearsOld': 'años',
          'login.signIn': 'Iniciar sesión',
          'login.username': 'Usuario',
          'login.password': 'Contraseña',
          'drawer.visits': 'Visitas',
          'drawer.about': 'Acerca de',
          'drawer.signOut': 'Cerrar Sesión',
          'drawer.visit': 'Visita',
          'about.developedBy': 'Desarrollado por:',
          'visit.detail': 'Detalle',
          'visit.map': 'Mapa',
          'visit.photos': 'Fotos',
          'visit.signature': 'Firma',
          'visit.camera': 'Cámara',
          'visit.finish': 'Finalizar',
          'visit.patient': 'Paciente:',
          'visit.address': 'Dirección:',
          'visit.age': 'Edad:',
          'visit.symptoms': 'Síntomas:',
          'visit.posibleCovid': 'Posible caso de COVID:',
          'visit.diagnostic': 'Diagnóstico:',
        },
        'en': {
          'common.yes': 'Yes',
          'common.no': 'No',
          'common.ok': 'Ok',
          'common.cancel': 'Cancel',
          'common.yearsOld': 'years old',
          'login.signIn': 'Sign in',
          'login.username': 'Username',
          'login.password': 'Password',
          'drawer.about': 'About',
          'drawer.signOut': 'Sign out',
          'drawer.visit': 'Visit',
          'about.developedBy': 'Developed by:',
          'visit.detail': 'Detail',
          'visit.map': 'Map',
          'visit.photos': 'Photos',
          'visit.signature': 'Signature',
          'visit.camera': 'Camera',
          'visit.finish': 'Finish',
          'visit.patient': 'Patient:',
          'visit.address': 'Address:',
          'visit.age': 'Age:',
          'visit.symptoms': 'Symptoms:',
          'visit.posibleCovid': 'Posible COVID case:',
          'visit.diagnostic': 'Diagnostic:',
        }
      };
}
